# Generated by Django 3.1.6 on 2021-02-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_auto_20210224_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto_venda',
            name='total',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
