# Generated by Django 3.1.6 on 2021-02-25 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_produto_venda_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto_venda',
            name='total',
            field=models.FloatField(),
        ),
    ]
