# Generated by Django 3.1.6 on 2021-02-25 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_auto_20210224_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='valor_total',
            field=models.FloatField(),
        ),
    ]
