# Generated by Django 3.1.6 on 2021-02-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0005_auto_20210225_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='volume_de_compra',
            field=models.IntegerField(),
        ),
    ]
