# Generated by Django 3.1.6 on 2021-03-12 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0006_auto_20210225_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='valor_pago',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
