# Generated by Django 3.1.6 on 2021-03-13 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0007_venda_valor_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='troco',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
