# Generated by Django 3.1.6 on 2021-02-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cep',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dd',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(max_length=9),
        ),
    ]
