# Generated by Django 3.1.6 on 2021-02-13 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20210213_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='numero',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='data_de_nascimento',
            field=models.DateField(),
        ),
    ]
